### ISSUE TITLE
Multiple `runAsWorker()` functions.

### ISSUE THREAD

**Issue by YuriGal** [lambci/sync-threads#1]
I have several async functions I need to make synchronous.

Is it possible to have multiple `runAsWorker()` functions in `worker.js` or a file has to be created per function?

Thanks!

**Comment by mhart** [comment]
Not possible unless you make the `runAsWorker` calls dependent on the `inputData`.

An easier way to do this (if you really had to only have one file) would be to just do something like this:

```js
runAsWorker(async ({ fn, data }) => {
  switch (fn) {
    case 'fn1':
      return await fn1(data)
    case 'fn2':
      return await fn2(data)
  }
})
```

**Comment by YuriGal** [comment]
This is beautiful, thank you! And thank you for the awesome library, it does miracles to our Lambda's cold starts.
